.TH "Key Code Constants" 3 "Thu Jul 10 2014" "Version v0.9.4" "Pixel Dust Game Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Key Code Constants \- 
.PP
Constants that represent special key codes\&.  

.SS "Variables"

.in +1c
.ti -1c
.RI "const \fBkey_Backspace\fP = 8"
.br
.ti -1c
.RI "const \fBkey_Break\fP = 1"
.br
.ti -1c
.RI "const \fBkey_Clear\fP = 4"
.br
.ti -1c
.RI "const \fBkey_Delete\fP = 127"
.br
.ti -1c
.RI "const \fBkey_DownArrow\fP = 31"
.br
.ti -1c
.RI "const \fBkey_End\fP = 3"
.br
.ti -1c
.RI "const \fBkey_Enter\fP = 13"
.br
.ti -1c
.RI "const \fBkey_Escape\fP = 27"
.br
.ti -1c
.RI "const \fBkey_F1\fP = 14"
.br
.ti -1c
.RI "const \fBkey_F10\fP = 23"
.br
.ti -1c
.RI "const \fBkey_F11\fP = 24"
.br
.ti -1c
.RI "const \fBkey_F12\fP = 25"
.br
.ti -1c
.RI "const \fBkey_F2\fP = 15"
.br
.ti -1c
.RI "const \fBkey_F3\fP = 16"
.br
.ti -1c
.RI "const \fBkey_F4\fP = 17"
.br
.ti -1c
.RI "const \fBkey_F5\fP = 18"
.br
.ti -1c
.RI "const \fBkey_F6\fP = 19"
.br
.ti -1c
.RI "const \fBkey_F7\fP = 20"
.br
.ti -1c
.RI "const \fBkey_F8\fP = 21"
.br
.ti -1c
.RI "const \fBkey_F9\fP = 22"
.br
.ti -1c
.RI "const \fBkey_FirstF\fP = 14"
.br
.ti -1c
.RI "const \fBkey_FirstPrintable\fP = 32"
.br
.ti -1c
.RI "const \fBkey_Help\fP = 5"
.br
.ti -1c
.RI "const \fBkey_Home\fP = 2"
.br
.ti -1c
.RI "const \fBkey_Insert\fP = 26"
.br
.ti -1c
.RI "const \fBkey_LastF\fP = 25"
.br
.ti -1c
.RI "const \fBkey_LeftArrow\fP = 28"
.br
.ti -1c
.RI "const \fBkey_Mute\fP = 7"
.br
.ti -1c
.RI "const \fBkey_PageDown\fP = 12"
.br
.ti -1c
.RI "const \fBkey_PageUp\fP = 11"
.br
.ti -1c
.RI "const \fBkey_Pause\fP = 6"
.br
.ti -1c
.RI "const \fBkey_Return\fP = 13"
.br
.ti -1c
.RI "const \fBkey_RightArrow\fP = 29"
.br
.ti -1c
.RI "const \fBkey_Tab\fP = 9"
.br
.ti -1c
.RI "const \fBkey_UpArrow\fP = 30"
.br
.in -1c
.SH "Detailed Description"
.PP 
Constants that represent special key codes\&. 


.SH "Variable Documentation"
.PP 
.SS "key_Backspace = 8"

.SS "key_Break = 1"

.SS "key_Clear = 4"

.SS "key_Delete = 127"

.SS "key_DownArrow = 31"

.SS "key_End = 3"

.SS "key_Enter = 13"

.SS "key_Escape = 27"

.SS "key_F1 = 14"

.SS "key_F10 = 23"

.SS "key_F11 = 24"

.SS "key_F12 = 25"

.SS "key_F2 = 15"

.SS "key_F3 = 16"

.SS "key_F4 = 17"

.SS "key_F5 = 18"

.SS "key_F6 = 19"

.SS "key_F7 = 20"

.SS "key_F8 = 21"

.SS "key_F9 = 22"

.SS "key_FirstF = 14"

.SS "key_FirstPrintable = 32"

.SS "key_Help = 5"

.SS "key_Home = 2"

.SS "key_Insert = 26"

.SS "key_LastF = 25"

.SS "key_LeftArrow = 28"

.SS "key_Mute = 7"

.SS "key_PageDown = 12"

.SS "key_PageUp = 11"

.SS "key_Pause = 6"

.SS "key_Return = 13"

.SS "key_RightArrow = 29"

.SS "key_Tab = 9"

.SS "key_UpArrow = 30"

.SH "Author"
.PP 
Generated automatically by Doxygen for Pixel Dust Game Engine from the source code\&.
