.TH "Networking" 3 "Thu Jul 10 2014" "Version v0.9.4" "Pixel Dust Game Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Networking \- 
.PP
Thing used for sending messages over the network\&.  

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBNetClient\fP"
.br
.RI "\fIa network endpoint that can initiate a connection \fP"
.ti -1c
.RI "class \fBNetConnection\fP"
.br
.RI "\fIsends data between two network endpoints \fP"
.ti -1c
.RI "class \fBNetServer\fP"
.br
.RI "\fIa network endpoint that can accept incoming connections \fP"
.in -1c
.SH "Detailed Description"
.PP 
Thing used for sending messages over the network\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for Pixel Dust Game Engine from the source code\&.
