.TH "Point" 3 "Thu Jul 10 2014" "Version v0.9.4" "Pixel Dust Game Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Point \- 
.PP
point for 2D coordinate system  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBOffset\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPoint\fP ()"
.br
.RI "\fIcreate with x = 0, y = 0 \fP"
.ti -1c
.RI "\fBPoint\fP (number \fBx\fP, number \fBy\fP)"
.br
.RI "\fIcreate and set x & y values \fP"
.ti -1c
.RI "\fBPoint\fP (number[] xy)"
.br
.RI "\fIcreate and set x & y values \fP"
.ti -1c
.RI "\fBPoint\fP (object xy)"
.br
.RI "\fIcreate and set x & y values \fP"
.ti -1c
.RI "number \fBdistance\fP (\fBPoint\fP point)"
.br
.RI "\fIget distance from another point \fP"
.ti -1c
.RI "\fBPoint\fP \fBprojection\fP (\fBPoint\fP point)"
.br
.RI "\fIdo a projection of a second point onto this point \fP"
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "number \fBx\fP"
.br
.ti -1c
.RI "number \fBy\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
point for 2D coordinate system 

\fBPoint\fP provides support for dealing with points as x, y floating point values in 2 dimensional space\&. The PDG coordinate space starts with the top left corner of the drawing port at Point(0,0) and the bottom left corner at Point( width, height );
.PP
 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBPoint\fP ()"

.PP
create with x = 0, y = 0 
.SS "\fBPoint\fP (numberx, numbery)"

.PP
create and set x & y values \fBParameters:\fP
.RS 4
\fIx\fP the horizontal coordinate 
.br
\fIy\fP the vertical coordinate 
.RE
.PP

.SS "\fBPoint\fP (number[]xy)"

.PP
create and set x & y values \fBParameters:\fP
.RS 4
\fIxy\fP an array of numbers with x as element 0 and y as element 1 
.RE
.PP

.SS "\fBPoint\fP (objectxy)"

.PP
create and set x & y values \fBParameters:\fP
.RS 4
\fIxy\fP an object with x and y members, for example: {x: 1, y: 4} 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "distance (\fBPoint\fPpoint)"

.PP
get distance from another point \fBParameters:\fP
.RS 4
\fIpoint\fP the other \fBPoint\fP 
.RE
.PP

.SS "projection (\fBPoint\fPpoint)"

.PP
do a projection of a second point onto this point 
.SH "Member Data Documentation"
.PP 
.SS "number x"

.SS "number y"


.SH "Author"
.PP 
Generated automatically by Doxygen for Pixel Dust Game Engine from the source code\&.
