.TH "Offset" 3 "Thu Jul 10 2014" "Version v0.9.4" "Pixel Dust Game Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Offset \- 
.PP
offset within a 2D coordinate system  

.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBPoint\fP, and \fBVector\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBOffset\fP ()"
.br
.ti -1c
.RI "\fBOffset\fP (number \fBx\fP, number \fBy\fP)"
.br
.ti -1c
.RI "\fBOffset\fP (number[] xy)"
.br
.ti -1c
.RI "\fBOffset\fP (object xy)"
.br
.ti -1c
.RI "\fBOffset\fP \fBadd\fP (\fBOffset\fP offset)"
.br
.ti -1c
.RI "\fBOffset\fP \fBassign\fP (\fBOffset\fP offset)"
.br
.ti -1c
.RI "\fBOffset\fP \fBdiv\fP (\fBOffset\fP offset)"
.br
.ti -1c
.RI "\fBOffset\fP \fBdividedby\fP (\fBOffset\fP offset)"
.br
.ti -1c
.RI "boolean \fBequals\fP (\fBOffset\fP offset)"
.br
.ti -1c
.RI "\fBOffset\fP \fBminus\fP (\fBOffset\fP offset)"
.br
.ti -1c
.RI "\fBOffset\fP \fBmul\fP (\fBOffset\fP offset)"
.br
.ti -1c
.RI "boolean \fBnotEquals\fP (\fBOffset\fP offset)"
.br
.ti -1c
.RI "\fBOffset\fP \fBplus\fP (\fBOffset\fP offset)"
.br
.ti -1c
.RI "\fBOffset\fP \fBsub\fP (\fBOffset\fP offset)"
.br
.ti -1c
.RI "\fBOffset\fP \fBtimes\fP (\fBOffset\fP offset)"
.br
.ti -1c
.RI "string \fBtoString\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "number \fBx\fP"
.br
.ti -1c
.RI "number \fBy\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
offset within a 2D coordinate system 

\fBOffset\fP provides support for dealing with offsets as x, y floating point values in 2 dimensional space\&. The PDG coordinate space starts with the top left corner of the drawing port at Point(0,0) and the bottom left corner at Point( width, height ); 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBOffset\fP ()"

.SS "\fBOffset\fP (numberx, numbery)"

.SS "\fBOffset\fP (number[]xy)"

.SS "\fBOffset\fP (objectxy)"

.SH "Member Function Documentation"
.PP 
.SS "\fBOffset\fP add (\fBOffset\fPoffset)"

.SS "\fBOffset\fP assign (\fBOffset\fPoffset)"

.SS "\fBOffset\fP div (\fBOffset\fPoffset)"

.SS "\fBOffset\fP dividedby (\fBOffset\fPoffset)"

.SS "boolean equals (\fBOffset\fPoffset)"

.SS "\fBOffset\fP minus (\fBOffset\fPoffset)"

.SS "\fBOffset\fP mul (\fBOffset\fPoffset)"

.SS "boolean notEquals (\fBOffset\fPoffset)"

.SS "\fBOffset\fP plus (\fBOffset\fPoffset)"

.SS "\fBOffset\fP sub (\fBOffset\fPoffset)"

.SS "\fBOffset\fP times (\fBOffset\fPoffset)"

.SS "string toString ()"

.SH "Member Data Documentation"
.PP 
.SS "number x"

.SS "number y"


.SH "Author"
.PP 
Generated automatically by Doxygen for Pixel Dust Game Engine from the source code\&.
