.TH "LogManager" 3 "Thu Jul 10 2014" "Version v0.9.4" "Pixel Dust Game Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LogManager \- 
.PP
used for doing logging with variable debug levels  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "string \fBbinaryDump\fP (BinaryString inData, int length=0, int bytesPerLine=20)"
.br
.RI "\fIget hex and ascii representations in a hex dump format\&. \fP"
.ti -1c
.RI "string \fBbinaryDump\fP (\fBMemBlock\fP inData, int length=0, int bytesPerLine=20)"
.br
.RI "\fIget hex and ascii representations in a hex dump format\&. \fP"
.ti -1c
.RI "number \fBgetLogLevel\fP ()"
.br
.RI "\fIreturn the current logging level \fP"
.ti -1c
.RI "\fBinitialize\fP (string inLogNameBase, int initMode=\fBLogManager\&.init_StdOut\fP)"
.br
.RI "\fIinitialize the \fBLogManager\fP, creating a new log file if necessary \fP"
.ti -1c
.RI "\fBLogManager\fP \fBsetLogLevel\fP (int inLogLevel)"
.br
.RI "\fIset the current logging level \fP"
.ti -1c
.RI "\fBwriteLogEntry\fP (int level, string category, string message)"
.br
.RI "\fIwrite a message to the log, if it is high enough priority \fP"
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const \fBinit_AppendToExisting\fP = 2"
.br
.RI "\fIif an existing file is present, append to it \fP"
.ti -1c
.RI "const \fBinit_CreateUniqueNewFile\fP = 0"
.br
.RI "\fIappend a timestamp to the base name to ensure a unique log files is created \fP"
.ti -1c
.RI "const \fBinit_OverwriteExisting\fP = 1"
.br
.RI "\fIif an existing file is present, overwrite it \fP"
.ti -1c
.RI "const \fBinit_StdErr\fP = 4"
.br
.RI "\fIdon't create a file, send log output to stderr \fP"
.ti -1c
.RI "const \fBinit_StdOut\fP = 3"
.br
.RI "\fIdon't create a file, send log output to stdout \fP"
.in -1c
.SS "Related Functions"
(Note that these are not member functions\&.) 
.in +1c
.ti -1c
.RI "\fBgetLogManager\fP"
.br
.RI "\fIget the singleton instance of the \fBLogManager\fP used by the pdg framework \fP"
.in -1c
.SH "Detailed Description"
.PP 
used for doing logging with variable debug levels 

\fBPrecondition:\fP
.RS 4
\fBAPI Stability: 3 - Stable\fP\&. The API has proven satisfactory, but cleanup in the underlying code may cause minor changes\&. Backwards-compatibility is guaranteed\&.
.RE
.PP
.SS "About Log Manager"
.PP
The Log Manager is a singleton object that generates date-time stamped log entries in a file or to stdout or stderr\&. The Aries log file format used is compact and very easy to search and filter using Unix command line tools like grep and tail\&.
.PP
.SS "Anatomy of a Log Entry:"
.PP
.PP
.nf
131023 09:33:51 1382520831167   I4  @LOGINIT   log initialized 2013/10/23 05:33:51 for pdg
   |     |         |            |      |          |
   |     |         |            |      |          +-- log message
   |     |         |            |      |
   |     |         |            |      +-- category
   |     |         |            | 
   |     |         |            +-- level code
   |     |         |           
   |     |         +-- millisecond time stamp
   |     |      
   |     +-- time
   |
   +-- date
.fi
.PP
.PP
The fields are:
.PP
.IP "1." 4
date -- the current date (GMT)
.IP "2." 4
time -- the current time (GMT)
.IP "3." 4
millisecond time stamp -- the number of milliseconds since system startup, as returned by \fBTimerManager\&.getMilliseconds()\fP
.IP "4." 4
level code -- a code representing the logging level for this entry, useful for filtering or log monitoring tools\&. This code is one of:
.IP "  1." 6
E0, E1, E2, E3 - Error (levels 0\&.\&.3)
.IP "  2." 6
I4, I5, I6, I7 - Inform (levels 4\&.\&.7)
.IP "  3." 6
V8 or V9 - Verbose (levels 8 & 9)
.IP "  4." 6
TRACE - level 10
.PP

.IP "5." 4
category -- a category of message, very useful for filtering\&. Generally these reflect areas of functionality that would be monitored or debugged separately, e\&.g\&.: 'AI', 'PATHING', 'TURN', etc\&.\&.\&. (See Note below)
.IP "6." 4
message -- the actual log message content
.PP
.PP
\fBNote:\fP
.RS 4
By convention, categories starting with @ are reserved for the messages generated by the \fBLogManager\fP itself\&. Also, categories FATAL, ERROR, WARN, LOG,INFO, DEBUG, and TRACE are generated by calls to \fBpdg\&.fatal()\fP, \fBpdg\&.error()\fP, \fBpdg\&.warn()\fP, \fBpdg\&.log()\fP, \fBpdg\&.info()\fP, \fBpdg\&.debug()\fP and \fBpdg\&.trace()\fP calls so using those values as categories is inadvisable\&.
.RE
.PP
.SS "Usage Examples:"
.PP
.PP
.nf
PDG terminal v0.9.3
> pdg.getLogManager().initialize("pdg", pdg.getLogManager().init_StdOut);
> pdg.getLogManager().setLogLevel(10);
131023 09:33:51 1382520831167   I4   @LOGINIT    log initialized 2013/10/23 05:33:51 for pdg
131023 09:33:51 1382520831168   I4   @BLDINFO    Build: [Oct 20 2013 11:55:02] Compiler: [GNU gcc] Target: [x86_64-apple-darwin]
131023 09:33:51 1382520831177   I4   @LOGLVL     setting log level to [10]
> pdg.getLogManager().writeLogEntry(1, "AI", "calculated chance of mission success 93%");
131023 09:34:14 1382520854276   E1   AI          calculated chance of mission success 93%
> pdg.fatal("test fatal error message");
131023 09:34:56 1382520896706   E0   FATAL       test fatal error message
> pdg.error("test error message");
131023 09:34:56 1382520896706   E1   ERROR       test error message
> pdg.warn("test warn message");
131023 09:35:52 1382520952860   E3   WARN        test warn message
> pdg.log("test log message");
131023 09:34:40 1382520880899   I4   LOG         test log message
> pdg.info("test info message");
131023 09:35:38 1382520938037   I5   INFO        test info message
> pdg.debug("test debug message");
131023 09:35:11 1382520911109   I7   DEBUG       test debug message
> pdg.trace("test trace message");
131023 09:35:27 1382520927229   V9   TRACE       test trace message
.fi
.PP
.PP
\fBSee Also:\fP
.RS 4
\fBTimerManager\&.getMilliseconds()\fP 
.PP
\fBpdg\&.captureConsole()\fP 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "string binaryDump (BinaryStringinData, intlength = \fC0\fP, intbytesPerLine = \fC20\fP)"

.PP
get hex and ascii representations in a hex dump format\&. \fBParameters:\fP
.RS 4
\fIinData\fP the binary string you want to dump 
.br
\fIlength\fP the number of bytes to dump, or 0 for entire contents of the BinaryString given 
.br
\fIbytesPerLine\fP how many bytes should be on each row of the output
.RE
.PP
\fBNote:\fP
.RS 4
a BinaryString is a JavaScript string where each character's integer value is from [0\&.\&.255]\&. Normal JavaScript strings are UTF-16, so they have 2 bytes per character, but for these purposes we ignore the high byte\&. 
.RE
.PP

.SS "string binaryDump (\fBMemBlock\fPinData, intlength = \fC0\fP, intbytesPerLine = \fC20\fP)"

.PP
get hex and ascii representations in a hex dump format\&. \fBParameters:\fP
.RS 4
\fIinData\fP the \fBMemBlock\fP you want to dump 
.br
\fIlength\fP the number of bytes to dump, or 0 for entire contents of the \fBMemBlock\fP given 
.br
\fIbytesPerLine\fP how many bytes should be on each row of the output 
.RE
.PP

.SS "getLogLevel ()"

.PP
return the current logging level \fBReturns:\fP
.RS 4
a numeric value representing the current logging level
.RE
.PP
\fBSee Also:\fP
.RS 4
\fBsetLogLevel()\fP 
.RE
.PP

.SS "initialize (stringinLogNameBase, intinitMode = \fC\fBLogManager\&.init_StdOut\fP\fP)"

.PP
initialize the \fBLogManager\fP, creating a new log file if necessary The following information is output to the log whenever the log manager is initialized: 
.PP
.nf
131023 09:33:51 1382520831167   I4   @LOGINIT    log initialized 2013/10/23 05:33:51 for pdg
131023 09:33:51 1382520831168   I4   @BLDINFO    Build: [Oct 20 2013 11:55:02] Compiler: [GNU gcc] Target: [x86_64-apple-darwin]

.fi
.PP
.PP
The @LOGINT line gives the local Date/Time (YYYY/MM/DD) when the Log Manager was initialized, and the 'for {name}' portion echoes the inLogNameBase passed in\&. The @BLDINFO reports the PDG version, app build date/time, compiler and target platform\&.
.PP
initMode is one (and only one) of:
.PP
.IP "\(bu" 2
init_CreateUniqueNewFile - appends a timestamp to log file base name to ensure a unique file is created
.IP "\(bu" 2
init_OverwriteExisting - if an existing file is present, overwrite it completely
.IP "\(bu" 2
init_AppendToExisting - if an existing file is present, append to it
.IP "\(bu" 2
init_StdOut - don't create a file, instead send log output to stdout
.IP "\(bu" 2
init_StdErr - don't create a file, instead send log output to stderr
.PP
.PP
\fBParameters:\fP
.RS 4
\fIinLogNameBase\fP this is used to help form the log file name 
.br
\fIinitMode\fP sets the mode the \fBLogManager\fP will use for outputting log entries 
.RE
.PP

.SS "setLogLevel (intinLogLevel)"

.PP
set the current logging level The log level is the lowest priority (highest numerical value) of log message that will actually be logged\&. Any lower priority (higher numeric value) messages will be filtered\&.
.PP
Whenever the log level is changed, a message reflecting that change in log level is echoed to the log, e\&.g\&.: 
.PP
.nf
131023 09:33:51 1382520831177   I4   @LOGLVL     setting log level to [10]

.fi
.PP
.PP
\fBSee Also:\fP
.RS 4
\fBgetLogLevel()\fP 
.PP
\fBwriteLogEntry()\fP 
.RE
.PP

.SS "writeLogEntry (intlevel, stringcategory, stringmessage)"

.PP
write a message to the log, if it is high enough priority Write a message to the log\&. If the level is lower priority (higher numeric value) than the current log level, the message will be filtered and not written to the log\&. Category is a short string used to define the area of functionality the logging is about, useful for debugging to narrow down the number of log entries you need to examine\&. Message is the actual log message
.PP
\fBNote:\fP
.RS 4
see \fBbinaryDump()\fP for converting binary data to a hex dump
.RE
.PP
Log levels (highest to lowest priority, lowest to highest numeric value): 
.PP
.nf
fatal = 0, 
error = 2, 
inform = 4, 
detail = 6, 
verbose = 8, 
trace = 10,

.fi
.PP
.PP
\fBParameters:\fP
.RS 4
\fIlevel\fP the priority level of this message (see above) 
.br
\fIcategory\fP the category of message 
.br
\fImessage\fP the actual log message 
.RE
.PP
\fBSee Also:\fP
.RS 4
\fBbinaryDump()\fP 
.PP
\fBsetLogLevel()\fP 
.PP
\fBpdg\&.fatal()\fP 
.PP
\fBpdg\&.error()\fP 
.PP
\fBpdg\&.warn()\fP 
.PP
\fBpdg\&.log()\fP 
.PP
\fBpdg\&.info()\fP 
.PP
\fBpdg\&.debug()\fP 
.PP
\fBpdg\&.trace()\fP 
.RE
.PP

.SH "Friends And Related Function Documentation"
.PP 
.SS "getLogManager\fC [related]\fP"

.PP
get the singleton instance of the \fBLogManager\fP used by the pdg framework \fBReturns:\fP
.RS 4
\fBLogManager\fP singleton object 
.RE
.PP

.SH "Member Data Documentation"
.PP 
.SS "init_AppendToExisting = 2"

.PP
if an existing file is present, append to it This flag is passed as initMode to \fBLogManager\&.initialize()\fP to cause the new log entries to be appended to an existing file\&. If no file exists, a new one will be created\&.
.PP
\fBSee Also:\fP
.RS 4
\fBinitialize()\fP 
.RE
.PP

.SS "init_CreateUniqueNewFile = 0"

.PP
append a timestamp to the base name to ensure a unique log files is created This flag is passed as initMode to \fBLogManager\&.initialize()\fP to cause the a new unique log file to be created\&.
.PP
\fBSee Also:\fP
.RS 4
\fBinitialize()\fP 
.RE
.PP

.SS "init_OverwriteExisting = 1"

.PP
if an existing file is present, overwrite it This flag is passed as initMode to \fBLogManager\&.initialize()\fP to cause the new log entries to overwrite an existing file with the same name\&. If no file exists, a new one will be created\&.
.PP
\fBSee Also:\fP
.RS 4
\fBinitialize()\fP 
.RE
.PP

.SS "init_StdErr = 4"

.PP
don't create a file, send log output to stderr This flag is passed as initMode to \fBLogManager\&.initialize()\fP to cause the log entries to be sent to stderr instead of to a file\&. No existing files are altered and no new files are created\&.
.PP
\fBSee Also:\fP
.RS 4
\fBinitialize()\fP 
.RE
.PP

.SS "init_StdOut = 3"

.PP
don't create a file, send log output to stdout This flag is passed as initMode to \fBLogManager\&.initialize()\fP to cause the log entries to be sent to stdout instead of to a file\&. No existing files are altered and no new files are created\&.
.PP
\fBSee Also:\fP
.RS 4
\fBinitialize()\fP 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Pixel Dust Game Engine from the source code\&.
