.TH "RotatedRect" 3 "Thu Jul 10 2014" "Version v0.9.4" "Pixel Dust Game Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RotatedRect \- 
.PP
rectangle with rotation for 2D coordinate system\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBRect\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRotatedRect\fP (\fBRect\fP rect=\fBRect\fP(0, 0), number rotationRadians=0\&.0, \fBOffset\fP cpOffset=null)"
.br
.ti -1c
.RI "\fBQuad\fP \fBgetQuad\fP ()"
.br
.ti -1c
.RI "\fBrotate\fP (number rotateRadians)"
.br
.ti -1c
.RI "\fBsetCenterOffset\fP (\fBOffset\fP cpOffset)"
.br
.ti -1c
.RI "\fBsetRotation\fP (number rotationRadians, \fBOffset\fP cpOffset=null)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "number \fBbottom\fP"
.br
.ti -1c
.RI "\fBPoint\fP \fBcenterOffset\fP"
.br
.ti -1c
.RI "number \fBleft\fP"
.br
.ti -1c
.RI "number \fBright\fP"
.br
.ti -1c
.RI "number \fBtop\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
rectangle with rotation for 2D coordinate system\&. 

\fBRotatedRect\fP is a class that provides support for dealing with rotating rectangles in 2 dimensional space\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBRotatedRect\fP (\fBRect\fPrect = \fC\fBRect\fP(0, 0)\fP, numberrotationRadians = \fC0\&.0\fP, \fBOffset\fPcpOffset = \fCnull\fP)"

.SH "Member Function Documentation"
.PP 
.SS "\fBQuad\fP getQuad ()"

.SS "rotate (numberrotateRadians)"

.SS "setCenterOffset (\fBOffset\fPcpOffset)"

.SS "setRotation (numberrotationRadians, \fBOffset\fPcpOffset = \fCnull\fP)"

.SH "Member Data Documentation"
.PP 
.SS "number bottom"

.SS "\fBPoint\fP centerOffset"

.SS "number left"

.SS "number right"

.SS "number top"


.SH "Author"
.PP 
Generated automatically by Doxygen for Pixel Dust Game Engine from the source code\&.
