.TH "Serialization" 3 "Thu Jul 10 2014" "Version v0.9.4" "Pixel Dust Game Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Serialization \- 
.PP
Things used for serializing and deserializing data\&.  

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDeserializer\fP"
.br
.RI "\fIdeserialize data from a serialized data stream \fP"
.ti -1c
.RI "class \fBISerializable\fP"
.br
.RI "\fIinterface for an object which can be serialized \fP"
.ti -1c
.RI "class \fBMemBlock\fP"
.br
.RI "\fIholds arbitrary blocks of memory \fP"
.ti -1c
.RI "class \fBSerializer\fP"
.br
.RI "\fIserialize data into memory \fP"
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBregisterSerializableClass\fP"
.br
.RI "\fIregister a particular class as implementing \fBISerializable\fP interface \fP"
.in -1c
.SH "Detailed Description"
.PP 
Things used for serializing and deserializing data\&. 


.SH "Function Documentation"
.PP 
.SS "registerSerializableClass\fC [related]\fP"

.PP
register a particular class as implementing \fBISerializable\fP interface 
.SH "Author"
.PP 
Generated automatically by Doxygen for Pixel Dust Game Engine from the source code\&.
